[신우주] ADD : SocialLoginView 작성
wecode-bootcamp-korea/24-2nd-TomorrowsNotebook-backend pull request #3
Opened 2021-09-17 08:56 UTC by shinwooju

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- SocialLoginviews.py 작성

## 수정 사항들 자세한 내용
9/17 
---
- kakaologin을 위한 뷰작성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-17 09:05 UTC, jamessoun93 commented
[장고 유닛테스트 노션 페이지](https://www.notion.so/wecode/3-Unit-Test-with-Django-5fd563537ac84cb8bef6f4159ac50a52) Mock 부분 참고하여 유닛테스트 포함시켜 올려주세요!

2021-09-27 01:17 UTC, S2-J1NG requested changes

2021-09-27 01:17 UTC, S2-J1NG commented on users/tests.py
> +        token = jwt.encode({"id" : flatform.social_id}, settings.SECRET_KEY, algorithm = ALGORITHM)
토큰은 user 테이블의 pk 값으로 만들어야 하지 않을까요? social_id도 유저의 개인정보이기 때문에 되도록 노출 되지 않는 것이 좋습니다.

2021-09-27 08:46 UTC, shinwooju commented on users/tests.py
> +        token = jwt.encode({"id" : flatform.social_id}, settings.SECRET_KEY, algorithm = ALGORITHM)
수정했습니다.

2021-09-27 09:00 UTC, S2-J1NG requested changes

2021-09-27 09:00 UTC, S2-J1NG commented on users/tests.py
> +        headers  = {"ERROR_Authorization" : "fail_token"}
이 경우는 카카오 토큰이 잘못된 경우인가요? 
잘못된 카카오 토큰으로 요청 했을 경우 mock path로 받는 데이터 확인해서  테스트 작성해주세요!
카카오 공식 문서에서 토큰 상태에 대한 설명 있습니다. 확인하고 반영해주세요!

https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#get-token-info

2021-09-27 09:00 UTC, S2-J1NG commented on users/tests.py
> +        self.assertEqual(response.status_code, 400)
이 부분도 카카오에서 전달해주는 데이터에 keyerror가 날 수 있는 경우 확인해서 mock patch 추가해서 작성해주세요
아래 내용 참고 하면 금방 되겠죠~?
```
@patch('user.views.requests')
    def test_kakao_signin_post_key_error(self, mocked_request):
        
        class MockedResponse:
            def json(self):
                return {
                        }
```

2021-09-27 09:47 UTC, S2-J1NG requested changes

2021-09-27 09:47 UTC, S2-J1NG commented on users/views.py
> +                return JsonResponse({"message" : "INVALID_TOKEN"}, status = 400)
이 부분을 삭제하고

2021-09-27 09:47 UTC, S2-J1NG commented on users/views.py
> +                return JsonResponse({"message" : "NOT_FOUND_RESPONSE"}, status = 404)
이 부분을 아래와 같이 수정하는게 invalid token 처리 하는 더 적절한 방법입니다!
json으로 응답 상세 정보를 받기 때문에 `response.json()` 형태가 됩니다!
이렇게 로직 수정하시고 postman으로 직접 테스트 해보세요!
```
account          = response.json()
         
            if account.get('code') == -401:
                return JsonResponse({'message':'INVALID_TOKEN'}, status=400)
```

2021-09-27 09:47 UTC, S2-J1NG commented on users/tests.py
> +        headers  = {"ERROR_Authorization" : "fail_token"}
view 수정 후 {"code" : -401}으로 테스트 하면 원하는 결과 값 나올거예요!

2021-09-27 10:23 UTC, shinwooju commented on users/views.py
> +                return JsonResponse({"message" : "NOT_FOUND_RESPONSE"}, status = 404)
테스트했습니당

2021-09-27 10:23 UTC, shinwooju commented on users/tests.py
> +        self.assertEqual(response.status_code, 400)
해결했습니다.

2021-09-27 10:23 UTC, shinwooju commented on users/tests.py
> +        headers  = {"ERROR_Authorization" : "fail_token"}
테스트결과 401 떳습니당!

2021-09-27 10:54 UTC, S2-J1NG approved these changes
LGTM🎉

2021-09-27 10:54 UTC, merged