[박지원]Add : Add libraries funtion
wecode-bootcamp-korea/24-2nd-TomorrowsNotebook-backend pull request #5
Opened 2021-09-28 09:30 UTC by jiwon5304

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

1.LibraryView/post
<img width="396" alt="1 LibraryView:post" src="https://user-images.githubusercontent.com/80395324/135061156-6bc0716c-dfdf-4004-9c95-000196bfb4ca.png">

2.libraryView/GET1
<img width="832" alt="2 libraryView:GET1" src="https://user-images.githubusercontent.com/80395324/135061293-f0378fa3-5d78-45dc-b624-5419293c17c6.png">

3.libraryView/GET2
<img width="297" alt="3 libraryView:GET2" src="https://user-images.githubusercontent.com/80395324/135061340-53a411de-b117-437c-8613-9bbb61d8059a.png">

4.ShelfDeleteView/post
<img width="463" alt="4 ShelfDeleteView:post" src="https://user-images.githubusercontent.com/80395324/135061474-9cad02b8-2ac0-4b94-8efd-3eba47aa0a1d.png">

5.ShelfListView/post
<img width="480" alt="5 ShelfListView:post" src="https://user-images.githubusercontent.com/80395324/135061531-a7e7734b-9479-46c1-96aa-6f2e729712ac.png">

6.ShelfListView/get
<img width="915" alt="6 ShelfListView:get" src="https://user-images.githubusercontent.com/80395324/135061580-e22ca242-cc63-4caa-8409-f5e0651ff21d.png">

7.LibraryListView/get
<img width="852" alt="7 LibraryListView:get" src="https://user-images.githubusercontent.com/80395324/135061658-6910fea9-8ffc-4cda-b754-868b972f15b7.png">

2021-09-29 01:48 UTC, S2-J1NG requested changes
csv 파일 모두 깃헙에서 삭제해주시고 conflict 해결 덜 된 부분 수정해주세요
반드시 기능별로 브랜치 나눠줘야 합니다.

2021-09-29 01:48 UTC, ghost commented on libraries/views.py
> +# from os import name
불필요한 주석은 삭제 해주세요~!

2021-09-29 01:48 UTC, ghost commented on tnb/urls.py
> +>>>>>>> 2b0f6fa (Add : Add libraries funtion)
conflict 해결 다 했는지 확인 중요합니다!
해결하는 중에 저장하게 되면 이렇게 코드에 남게 됩니다

2021-09-29 01:48 UTC, S2-J1NG commented on libraries/views.py
> +        )
같은 책장 이름은 생성 안 되게 막는 건 어떨까요?
비지니스 로직으로 생각을 해봐도 유저가 서재에 넣은 도서를 구분하기 위해 책장을 만드는데  굳이 같은 책장 이름으로 다른 책을 넣는 경우가 있을까요? 동일한 책장 이름을 입력하는 경우 예외 처리 하는 로직으로 수정하는 게 더 적절해 보입니다.

2021-09-29 01:48 UTC, S2-J1NG commented on libraries/views.py
> +        })
책장을 생성하고 나서 유저의 전체 책장 리스트 전달은 get 통신으로 바꿔서 진행해주세요
post 액션이 끝난 뒤에는 별도의 results 값이 있을 필요가 없습니다.

2021-09-29 01:48 UTC, S2-J1NG commented on libraries/views.py
> +            isExc =[]
변수명은 다른 사람이 알아볼 수 있게 작성해주세요!

2021-09-29 01:48 UTC, S2-J1NG commented on libraries/views.py
> +            shelves_list = []
전체 도서 api와 전체 책장 api는 분리해서 작성 해주세요
append보다 list comprehension 사용해서 코드 간결화 해주세요~!

2021-09-29 01:48 UTC, S2-J1NG commented on libraries/views.py
> +            return JsonResponse({"MESSAGE": "SUCCESS"}, status=201)
key에러나 잘못된 책장 번호가 들어오는 경우 생각해서 예외 처리로 잡아주세요

2021-09-29 01:48 UTC, S2-J1NG commented on libraries/views.py
> +        return JsonResponse({"MESSAGE": "SUCCESS"}, status=201)
책 상세 페이지에서 도서를 책장에 추가 하는 로직이죠?
책장 만들기 부분에서 책장에 중복 이름 허용 불가 조건을 줬기 때문에 filter가 아닌 get으로 특정 책장 하나만 가져올 수 있겠죠?
이 부분도 키에러나 도서 정보가 잘못 되었을 경우, 없는 책장 이름인 경우 등의 예외 잡아주세요

2021-09-29 01:48 UTC, S2-J1NG commented on libraries/views.py
> +class LibraryListView(View):
이 두 로직의 차이점이 뭔가요?

2021-09-29 02:51 UTC, jiwon5304 commented on libraries/views.py
> +# from os import name
네 삭제 했습니다!

2021-09-29 02:52 UTC, jiwon5304 commented on tnb/urls.py
> +>>>>>>> 2b0f6fa (Add : Add libraries funtion)
네 확인했습니다.

2021-09-29 04:50 UTC, jiwon5304 commented on libraries/views.py
> +        )
네 처리했습니다!

2021-09-29 04:58 UTC, jiwon5304 commented on libraries/views.py
> +        })
네 get 통신 통해 책장값 전달하는 것으로 프론트랑 협의했습니다. 수정완료입니다!

2021-09-29 10:16 UTC, jiwon5304 commented on libraries/views.py
> +            return JsonResponse({"MESSAGE": "SUCCESS"}, status=201)
네 예외처리 했습니다.

2021-09-29 10:16 UTC, jiwon5304 commented on libraries/views.py
> +            isExc =[]
네 수정했습니다.

2021-09-29 20:00 UTC, jiwon5304 commented on libraries/views.py
> +            shelves_list = []
네 분리완료했습니다.

2021-09-30 01:28 UTC, S2-J1NG requested changes
db_uploader 파일도 깃허브에 올라오면 안 됩니다~! 삭제 후 다시 올려주세요!

2021-09-30 07:04 UTC, jiwon5304 commented
db_uploader 삭제했습니다!

2021-09-30 07:34 UTC, S2-J1NG commented
conflict 해결해주세요!

2021-09-30 08:53 UTC, merged